For every increase in point per loan, how much more down would you have to increase. 

1. Develop montly mortgage cost given home cost
2. How much more down have to increase (%) for every increase in (%) 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class LoanDown:
    def __init__(self, home_price, loan_amount, loan_interest_rate, 
                 loan_length_in_years, taxes_and_insurance):
        self.home_price = home_price
        self.loan_amount = loan_amount
        self.loan_interest_rate = loan_interest_rate
        self.loan_length_in_years = loan_length_in_years
        self.taxes_and_insurance = taxes_and_insurance
        self.monthly_payment = self.monthly_mortgage()
        self.down_payment = home_price - loan_amount
        
    def monthly_mortgage(self):
        """ 
        monthly mortgage calculator: 
        M= P[r(1+r)^n/((1+r)^n)-1)]
        """
        monthly_interest_rate = self.loan_interest_rate/12
        num_payments = self.loan_length_in_years * 12
        interest_scale =(1+monthly_interest_rate) ** num_payments 
        numerator = monthly_interest_rate * interest_scale 
        denominator = interest_scale-1 
        monthly = self.loan_amount * (numerator/denominator)
        return monthly
    

In [3]:
def monthly_mortgage(loan_interest_rate, loan_length_in_years, loan_amount):
    """ 
    monthly mortgage calculator: 
    M= P[r(1+r)^n/((1+r)^n)-1)]
    """
    monthly_interest_rate = loan_interest_rate/100/12
    num_payments = loan_length_in_years * 12
    interest_scale =(1+monthly_interest_rate) ** num_payments 
    numerator = monthly_interest_rate * interest_scale 
    denominator = interest_scale-1 
    monthly = loan_amount * (numerator/denominator)
    return round(monthly,2)

def down_calculator(loan_interest_rate, loan_length_in_years, monthly_payment_target):
    monthly_interest_rate = loan_interest_rate/100/12
    num_payments = loan_length_in_years * 12
    interest_scale =(1+monthly_interest_rate) ** num_payments 
    numerator = monthly_interest_rate * interest_scale 
    denominator = interest_scale-1 
    loan_amount = monthly_payment_target / (numerator/denominator)
    return round(loan_amount,2)

In [40]:
target_home_price = 1500000
down_percent = 50
loan_amount = target_home_price * (1 - down_percent/100)
current_interest_rate = 6
future_interest_rate = 7

current_monthly = monthly_mortgage(current_interest_rate, 30, loan_amount)
future_home = round(down_calculator(future_interest_rate, 30, current_monthly) / ((100-down_percent)/100),2)

print('monthly mortgage for a current interest rate of', str(current_interest_rate), 'for a ', str(target_home_price), 'is', str(current_monthly))
print('if we kept that monthly and assumed future interest rate of', str(future_interest_rate),'...')
print('the max home price you could afford would be', str(future_home))
print('so to afford the same price home, youd have to save $', round(target_home_price-future_home,2))
print('meaning your buying power is ', str(round((future_home/target_home_price)*100,2)),'% of what it is now')

monthly mortgage for a current interest rate of 6 for a  1500000 is 4496.63
if we kept that monthly and assumed future interest rate of 7 ...
the max home price you could afford would be 1351755.04
so to afford the same price home, youd have to save $ 148244.96
meaning your buying power is  90.12 % of what it is now


In [43]:
bp = []
for future_interest_rate in np.linspace(3, 5.25, 10):
    current_interest_rate = 3
    current_monthly = monthly_mortgage(current_interest_rate, 30, loan_amount)
    future_home = round(down_calculator(future_interest_rate, 30, current_monthly) / .8,2)
    bp.append(round((future_home/target_home_price)*100,2))
    
print(np.linspace(3, 5.25, 10))
print(np.diff(bp))

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25]
[-1.95 -1.87 -1.78 -1.71 -1.63 -1.55 -1.5  -1.42 -1.37]


In [44]:
print(np.diff(bp))


print(f'for every .25% increase in interest rate. we expect a marginal drop in buying power of approximately {round(np.mean(np.diff(bp)),2)}%')
print('meaning that if you could buy a 1M house and interest rate went up, the max house you could afford would be 970k')

[-1.95 -1.87 -1.78 -1.71 -1.63 -1.55 -1.5  -1.42 -1.37]
for every .25% increase in interest rate. we expect a marginal drop in buying power of approximately -1.64%
meaning that if you could buy a 1M house and interest rate went up, the max house you could afford would be 970k
